### ISSUE TITLE
创建算法目录，使用js解题算法

### ISSUE THREAD

**Issue by hc-advokate** [chao921125/chao921125#1]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>数组去重</title>
</head>
<body>
  <div id="primary"></div>
  <div id="sort"></div>
  <div id="changed"></div>
<script>
  ;((e) => {
    // 解题思路：双游标记录，比对左右游标的值是否相等，相等的时候：左侧游标不变，右侧游标+1。不相等的时候：左侧游标+1，将右侧游标的值赋予左侧游标+1后的值。
    // 前提：两者游标初始须相邻。额外扩展，数组的删除。
    // 空间复杂度和时间复杂度就是O(1)和O(n)
    let removeDuplicates = (nums) => {
      // nums = [...new Set(nums)];
      // Map
      if (!nums || nums.length === 0) return 0;
      let l = 0;
      for (let r = 1; r < nums.length; r++) {
        if (nums[l] !== nums[r]) {
          l++;
          nums[l] = nums[r];
        }
      }
      // pop(),shift()
      // slice(),filter(),
      // delete
      let pIndex = nums.length;
      let dIndex = nums.slice(l+1).length;
      document.querySelector("#changed").innerText = "去重后数组为：" + nums.slice(0, pIndex - dIndex);
    };
    let arr = [];
    for (let i = 0; i < 20; i++) {
      arr.push(Math.floor(Math.random() * i + 1));
    }
    document.querySelector("#primary").innerText = "原数组为：" + arr;
    arr = arr.sort((a, b) => {return a - b});
    document.querySelector("#sort").innerText = "排序后数组为：" + arr;
    removeDuplicates(arr);
  })(window);
</script>
</body>
</html>

**Comment by hc-advokate** [comment]
[algorithm-reset.txt](https://github.com/chao921125/web-study/files/8988523/algorithm-reset.txt)

**Comment by chao921125** [comment]
已合并
